import { Cancons } from './cancons';

export const CANCONS: Cancons[] = [
    {id: 1, nom: 'Fantasia', artista: 'Ozuna', album: 'Nibiru', any: 2019, imatge: 'assets/imatges/nibiru.jpg', descripcio: '«Fantasía» es una cançó del cant puertorriqueño Ozuna.1 Se llançà el 28 de novembre de 2019 com el cinqué senzill del seu tercer àlbum de estudi Nibiru.', musica: 'http://localhost:8888/fantasiaOzuna.mp3'},
    {id: 2, nom: 'Bohemian Rhapsody', artista: 'Queen', album: 'Bohemian Rhapsody', any: 2018, imatge: 'assets/imatges/bohemian.jpg', descripcio: 'Bohemian Rhapsody té una estructura narrativa de monòleg interior dins un malson. La forma musical és més afí a una rapsòdia clàssica que no pas a música pop.', musica: 'http://localhost:8888/bohemian.mp3'},
    {id: 3, nom: 'Hoy no me puedo levantar', artista: 'Mecano', album: 'Mecano', any: 1982, imatge: 'assets/imatges/mecano.jpg', descripcio: 'Va ser el primer senzill llençat per el grup espanyol. Van vendre 35 mil copies, es considera un dels majors èxits del grup.', musica: 'http://localhost:8888/hnmpl.mp3'},
    {id: 4, nom: 'Wake me up', artista: 'Avicii', album: 'True', any: 2013, imatge: 'assets/imatges/true.png', descripcio: 'Wake Me Up és una cançó del músic suec Avicii que va ser llançada el dia 28 de juny de 2013 com a primer senzill del seu àlbum True. Compta amb la veu de Aloe Blacc i la guitarra de Mike Eizinger, del grup Incubus..', musica: 'http://localhost:8888/wake.mp3'},
    {id: 5, nom: 'Somebody To Love', artista: 'Queen', album: 'Bohemian Rhapsody', any: 2018, imatge: 'assets/imatges/bohemian.jpg', descripcio: 'És una composició rock, amb aires de gospel, en la qual la veu de Freddie Mercury (el seu compositor) s´esplaia amb escales de veu molt complicades amb cors fets per ell mateix, Brian May i Roger Taylor.', musica: 'http://localhost:8888/somebody.mp3'},
    {id: 6, nom: 'Hey Brother', artista: 'Avicii', album: 'True', any: 2013, imatge: 'assets/imatges/true.png', descripcio: 'És una cançó feta pel disc-jockey i productor discogràfic suec Avicii, inclòs en el seu àlbum debut True. Compta amb la col·laboració, encara que sense acreditar, de el cantant de bluegrass Dan Tyminski, integrant de la banda Alison Krauss and Union Station', musica: 'http://localhost:8888/brother.mp3'},
    {id: 7, nom: 'Perdido en mi habitación', artista: 'Mecano', album: 'Mecano', any: 1982, imatge: 'assets/imatges/mecano.jpg', descripcio: 'Va ser el primer senzill llençat per el grup espanyol. Van vendre 35 mil copies, es considera un dels majors èxits del grup.', musica: 'http://localhost:8888/perdido.mp3'},
    {id: 8, nom: 'Te soñé de nuevo', artista: 'Ozuna', album: 'Nibiru', any: 2019, imatge: 'assets/imatges/nibiru.jpg', descripcio: '«Te soñé de nuevo» és una cançó del cantant porto-riqueny Ozuna. Es va llançar el 6 de juny de 2019, a través de Sony Music Latin, com el tercer senzill del seu tercer àlbum de estudi Nibiru. Va aconseguir la posició setze en la llista de Billboard Hot Latin Songs dels Estats Units', musica: 'http://localhost:8888/anoche.mp3'},
];