import { Cancons } from './cancons';

export const CANCONS: Cancons[] = [
    {id: 1, nom: 'Fantasia', artista: 'Ozuna', album: 'Nibiru', any: 2019, imatge: 'assets/imatges/nibiru.jpg', descripcio: 'És una cançó i senzill realitzat per als Backstreet Boys del seu tercer àlbum Millenium.', musica: 'http://localhost:8888/fantasiaOzuna.mp3'},
    {id: 2, nom: 'Bohemian Rhapsody', artista: 'Queen', album: 'Bohemian Rhapsody', any: 2018, imatge: 'assets/imatges/bohemian.jpg', descripcio: 'Bohemian Rhapsody té una estructura narrativa de monòleg interior dins un malson. La forma musical és més afí a una rapsòdia clàssica que no pas a música pop.', musica: 'http://localhost:8888/bohemian.mp3'},
    {id: 3, nom: 'Hoy no me puedo levantar', artista: 'Mecano', album: 'Mecano', any: 1982, imatge: 'assets/imatges/mecano.jpg', descripcio: 'Va ser el primer senzill llençat per el grup espanyol. Van vendre 35 mil copies, es considera un dels majors èxits del grup.', musica: 'http://localhost:8888/hnmpl.mp3'},
    {id: 4, nom: 'Wake me up', artista: 'Avicii', album: 'True', any: 2013, imatge: 'assets/imatges/true.png', descripcio: 'Va ser el primer senzill llençat per el grup espanyol. Van vendre 35 mil copies, es considera un dels majors èxits del grup.', musica: 'http://localhost:8888/wake.mp3'},
    {id: 5, nom: 'Somebody To Love', artista: 'Queen', album: 'Bohemian Rhapsody', any: 2018, imatge: 'assets/imatges/bohemian.jpg', descripcio: 'És una composició rock, amb aires de gospel, en la qual la veu de Freddie Mercury (el seu compositor) s´esplaia amb escales de veu molt complicades amb cors fets per ell mateix, Brian May i Roger Taylor.', musica: 'http://localhost:8888/somebody.mp3'},
    {id: 6, nom: 'Hey Brother', artista: 'Avicii', album: 'True', any: 2013, imatge: 'assets/imatges/true.png', descripcio: 'Va ser el primer senzill llençat per el grup espanyol. Van vendre 35 mil copies, es considera un dels majors èxits del grup.', musica: 'http://localhost:8888/brother.mp3'},
    {id: 7, nom: 'Perdido en mi habitación', artista: 'Mecano', album: 'Mecano', any: 1982, imatge: 'assets/imatges/mecano.jpg', descripcio: 'Va ser el primer senzill llençat per el grup espanyol. Van vendre 35 mil copies, es considera un dels majors èxits del grup.', musica: 'http://localhost:8888/perdido.mp3'},
    {id: 8, nom: 'Te soñé de nuevo', artista: 'Ozuna', album: 'Nibiru', any: 2019, imatge: 'assets/imatges/nibiru.jpg', descripcio: 'És una cançó i senzill realitzat per als Backstreet Boys del seu tercer àlbum Millenium.', musica: 'http://localhost:8888/anoche.mp3'},
];